### ISSUE TITLE
Backdoor Design

### ISSUE THREAD

**Issue by dohki** [KAIST-IS521/2019-Spring#50]
분명히 domain knowledge를 필요로 하는 backdoor를 만들지 말라고 들었던 거 같은데
IS2team의 hard backdoor는 왜 [Wiener's attack](https://en.wikipedia.org/wiki/Wiener%27s_attack)을 이용한 것인지 궁금합니다.
Crypto attack은 domain knowledge가 아닌가요?

**Comment by sangkilc** [comment]
1. We didn't say so. We said you should avoid creating "hacking problems".
2. We believe the IS2team's backdoor contains reasonable amount of information to drive students towards Wiener's attack. Furthermore, the backdoor gives a good lesson to everyone, which will be shared with everyone during the presentation session (I believe).
3. To compare with what you have created during the design sessions, we found that those problems that you created earlier did not give any good insight with regard to our course principle: security by design/engineering. They were more like a mind-blowing puzzle, which has its own value, but does not align with our course principle.
